SELECT DNUMBER, DNAME, SSN, FNAME + ' ' + LNAME AS [MANAGER NAME] FROM DEPARTMENT JOIN EMPLOYEE ON MGRSSN = SSN;

SELECT DNAME, PNAME FROM DEPARTMENT JOIN PROJECT ON DNUMBER = DNUM;

SELECT DEPENDENT.*, FNAME + ' ' + LNAME AS [EMPLOYEE NAME] FROM DEPENDENT JOIN EMPLOYEE ON ESSN = SSN;

SELECT PNUMBER, PNAME, PLOCATION FROM PROJECT WHERE PLOCATION IN ('Cairo', 'Alex');

SELECT * FROM PROJECT WHERE PNAME LIKE 'A%';

SELECT * FROM EMPLOYEE WHERE DNO = 30 AND SALARY BETWEEN 1000 AND 2000;

SELECT FNAME + ' ' + LNAME AS [EMPLOYEE NAME] FROM EMPLOYEE JOIN WORKS_ON ON SSN = ESSN JOIN PROJECT ON PNO = PNUMBER WHERE DNO = 10 AND HOURS >= 10 AND PNAME = 'Al Rabwah';

SELECT E.FNAME + ' ' + E.LNAME AS [EMPLOYEE NAME] FROM EMPLOYEE E JOIN EMPLOYEE S ON E.SUPERSSN = S.SSN WHERE S.FNAME + ' ' + S.LNAME = 'Kamel Mohamed';

SELECT E.FNAME + ' ' + E.LNAME AS [EMPLOYEE NAME], P.PNAME AS [PROJECT NAME] FROM EMPLOYEE E JOIN WORKS_ON W ON E.SSN = W.ESSN JOIN PROJECT P ON W.PNO = P.PNUMBER ORDER BY P.PNAME;

SELECT P.PNUMBER, D.DNAME, E.LNAME, E.ADDRESS, E.BDATE FROM PROJECT P JOIN DEPARTMENT D ON P.DNUM = D.DNUMBER JOIN EMPLOYEE E ON D.MGRSSN = E.SSN WHERE P.PLOCATION = 'Cairo';

SELECT E.* FROM EMPLOYEE E JOIN DEPARTMENT D ON E.SSN = D.MGRSSN;

SELECT E.FNAME + ' ' + E.LNAME AS [EMPLOYEE NAME], DEP.* FROM EMPLOYEE E LEFT JOIN DEPENDENT DEP ON E.SSN = DEP.ESSN;

SELECT FNAME, LNAME, SALARY FROM EMPLOYEE;

SELECT FNAME + ' ' + LNAME AS [EMPLOYEE NAME] FROM EMPLOYEE WHERE DNO = 10;

SELECT P.PNAME, COUNT(W.ESSN) AS [NUMBER OF EMPLOYEES] FROM PROJECT P LEFT JOIN WORKS_ON W ON P.PNUMBER = W.PNO GROUP BY P.PNAME;

SELECT D.DNAME, MAX(E.SALARY) AS [MAX SALARY], MIN(E.SALARY) AS [MIN SALARY], AVG(E.SALARY) AS [AVERAGE SALARY] FROM DEPARTMENT D JOIN EMPLOYEE E ON D.DNUMBER = E.DNO GROUP BY D.DNAME;

SELECT FNAME + ' ' + LNAME AS [EMPLOYEE NAME] FROM EMPLOYEE WHERE SUPERSSN IS NULL;

SELECT D.DNAME, COUNT(E.SSN) AS [NUMBER OF EMPLOYEES] FROM DEPARTMENT D LEFT JOIN EMPLOYEE E ON D.DNUMBER = E.DNO GROUP BY D.DNAME;

SELECT E.FNAME + ' ' + E.LNAME AS [EMPLOYEE NAME], P.PNAME AS [PROJECT NAME] FROM EMPLOYEE E JOIN WORKS_ON W ON E.SSN = W.ESSN JOIN PROJECT P ON W.PNO = P.PNUMBER;

SELECT FNAME + ' ' + LNAME AS [EMPLOYEE NAME] FROM EMPLOYEE WHERE SALARY > 3000;

SELECT E.FNAME + ' ' + E.LNAME AS [EMPLOYEE NAME], S.FNAME + ' ' + S.LNAME AS [SUPERVISOR NAME] FROM EMPLOYEE E LEFT JOIN EMPLOYEE S ON E.SUPERSSN = S.SSN;

SELECT E.FNAME + ' ' + E.LNAME AS [EMPLOYEE NAME], P.PNAME AS [PROJECT NAME], W.HOURS FROM EMPLOYEE E JOIN WORKS_ON W ON E.SSN = W.ESSN JOIN PROJECT P ON W.PNO = P.PNUMBER;

SELECT * FROM EMPLOYEE ORDER BY SALARY DESC;

SELECT D.DNAME FROM DEPARTMENT D JOIN EMPLOYEE E ON D.DNUMBER = E.DNO GROUP BY D.DNAME HAVING COUNT(E.SSN) > 3;

SELECT P.PNAME FROM PROJECT P JOIN WORKS_ON W ON P.PNUMBER = W.PNO GROUP BY P.PNAME HAVING COUNT(W.ESSN) > 2;

SELECT D.DNAME FROM DEPARTMENT D JOIN EMPLOYEE E ON D.DNUMBER = E.DNO GROUP BY D.DNAME HAVING AVG(E.SALARY) > 3000;
