CREATE VIEW v_EmployeeDepartmentDetails AS SELECT E.SSN, E.FNAME + ' ' + E.LNAME AS EMPLOYEENAME, E.SALARY, E.SEX, D.DNAME FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DNO = D.DNUMBER;

CREATE VIEW v_DepartmentProjectSummary AS SELECT D.DNUMBER, D.DNAME, E.FNAME + ' ' + E.LNAME AS MANAGERNAME,COUNT(P.PNUMBER) AS TOTALPROJECTS FROM DEPARTMENT D JOIN EMPLOYEE E ON D.DNUMBER = E.DNO LEFT JOIN PROJECT P ON D.DNUMBER = P.DNUM GROUP BY D.DNUMBER, D.DNAME, E.FNAME, E.LNAME;

CREATE VIEW v_ProjectWorkloadSummary AS SELECT P.PNUMBER, P.PNAME, D.DNAME, COUNT(DISTINCT W.ESSN) AS TOTALEMPLOYEE, SUM(W.HOURS) AS TOTALHOURS FROM PROJECT P JOIN DEPARTMENT D ON P.DNUM = D.DNUMBER LEFT JOIN WORKS_ON W ON P.PNUMBER = W.PNO GROUP BY P.PNUMBER, P.PNAME, D.DNAME;

CREATE VIEW v_EmployeeSupervisorInfo AS SELECT E.FNAME + ' ' + E.LNAME AS 'EMPLOYEE NAME', E.SALARY AS 'EMPLOYEE SALARY',
S.FNAME + ' ' + S.LNAME AS 'SUPERVISOR NAME', S.SALARY AS 'SUPERVISOR SALARY' FROM EMPLOYEE E JOIN EMPLOYEE S ON E.SUPERSSN = S.SSN WHERE E.SUPERSSN IS NOT NULL;

CREATE VIEW v_EmployeeDependentsOverview AS SELECT E.SSN, E.FNAME + ' ' + E.LNAME AS 'EMPLOYEE NAME', D.DNAME, COUNT(DEP.ESSN) AS 'TOTAL DEPENDENTS' FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DNO = D.DNUMBER LEFT JOIN DEPENDENT DEP ON E.SSN = DEP.ESSN GROUP BY E.SSN, E.FNAME, E.LNAME, D.DNAME;

CREATE FUNCTION fn_CalculateAnnualSalary(@SSN INT) 
RETURNS DECIMAL(10, 2) AS 
BEGIN 
	DECLARE @AnnualSallary DECIMAL(10, 2);

	SELECT @AnnualSallary = SALARY * 12
	FROM EMPLOYEE WHERE SSN = @SSN
	RETURN ISNULL(@AnnualSallary, 0);
END;

CREATE FUNCTION fn_GetEmployeeTotalHours(@ESSN INT)
RETURNS DECIMAL(10, 2) AS 
BEGIN
	DECLARE @TOTALHOURS DECIMAL(10, 2);

	SELECT @TOTALHOURS = SUM(HOURS)
	FROM dbo.WORKS_ON WHERE ESSN = @ESSN
	RETURN ISNULL(@TOTALHOURS, 0);
END;


CREATE FUNCTION dbo.fn_GetEmployeesByDepartment(@DNumber INT) RETURNS TABLE AS RETURN(
	SELECT SSN, FNAME + ' ' + LNAME AS 'FULL NAME', SALARY, SEX, ADDRESS
	FROM EMPLOYEE WHERE DNO = @DNumber
	);



CREATE FUNCTION dbo.fn_GetProjectsByLocation(@Location VARCHAR(50)) RETURNS TABLE AS 
RETURN(
	SELECT P.PNUMBER, P.PNAME, P.PLOCATION, D.DNAME
	FROM PROJECT P JOIN DEPARTMENT D
	ON P.DNUM = D.DNUMBER
	WHERE P.PLOCATION = @Location
);


CREATE FUNCTION fn_GetWorkloadCategory(@ESSN INT) RETURNS VARCHAR(20) AS BEGIN
	DECLARE @TOTALHOURS DECIMAL(10, 2);

	SELECT @TOTALHOURS = SUM(HOURS)
	FROM WORKS_ON WHERE ESSN = @ESSN

	SET @TOTALHOURS = ISNULL(@TOTALHOURS, 0);

	IF @TOTALHOURS >= 40
		RETURN 'FULL WORKLEAD';
	IF @TOTALHOURS BETWEEN 1 AND 39
		RETURN 'PARTIAL WORKLEAD';
	RETURN 'NO WORKLEAD';
END;


CREATE PROCEDURE sp_GetEmployeesBySalary @MinSalary INT AS 
BEGIN 
	SELECT SSN, FNAME + ' ' + LNAME, SALARY, DNO
	FROM EMPLOYEE 
	WHERE SALARY >= @MinSalary;
END;

CREATE PROCEDURE sp_2AddNewEmployee
	@FNAME VARCHAR(15), @LNAME VARCHAR(15), @SSN INT,
	@SALARY DECIMAL(10, 2), @SEX CHAR(1), @DNO INT AS
BEGIN
	IF NOT EXISTS(SELECT 1 FROM DEPARTMENT WHERE DNUMBER = @DNO)
	BEGIN
		PRINT 'Department Does Not Exists'
		RETURN;
	END;

	IF EXISTS(SELECT 1 FROM EMPLOYEE WHERE SSN = @SSN)
	BEGIN
		PRINT 'Employee SSN Already Exists';
	END;

	INSERT INTO EMPLOYEE(FNAME, LNAME, SSN, SALARY, SEX, DNO)
	VALUES(@FNAME, @LNAME, @SSN, @SALARY, @SEX, @DNO);
	PRINT 'EMPLOYEE ADDED SUCCESSFULLY';
END;

CREATE PROCEDURE sp_UpdateEmployeeSalaryByDept 
	@DNumber INT, @BonusAmount DECIMAL(10, 2), 
	@UpdatedCount INT OUTPUT AS
BEGIN
	SET @UpdatedCount = 0;

	IF NOT EXISTS(SELECT 1 FROM DEPARTMENT WHERE DNUMBER = @DNumber)
	BEGIN
		PRINT 'Department Not Found';
		RETURN;
	END;

	UPDATE EMPLOYEE 
	SET SALARY = SALARY + @BonusAmount
	WHERE DNO = @DNumber;

	SET @UpdatedCount = @@ROWCOUNT;
END;




CREATE PROCEDURE sp_AssignEmployeeToProject
@ESSN INT, @PNO INT, @Hours DECIMAL(10,2) AS
BEGIN
        IF NOT EXISTS (SELECT 1 FROM EMPLOYEE WHERE SSN = @ESSN)
    BEGIN
        PRINT 'Employee Not Found';
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM PROJECT WHERE PNUMBER = @PNO)
    BEGIN
        PRINT 'Project Not Found';
        RETURN;
    END;

    IF EXISTS (SELECT 1 FROM WORKS_ON WHERE ESSN = @ESSN AND PNO = @PNO)
    BEGIN
        UPDATE WORKS_ON SET HOURS = @Hours
        WHERE ESSN = @ESSN AND PNO = @PNO;
        PRINT 'Assignment Updated Successfully';
    END
    ELSE
    BEGIN
        INSERT INTO WORKS_ON (ESSN, PNO, HOURS)
        VALUES (@ESSN, @PNO, @Hours);
        PRINT 'Assignment Added Successfully';
END;
END


CREATE PROCEDURE sp_RemoveDependent
@ESSN INT, @DepName VARCHAR(15), @RemainingCount INT OUTPUT AS
BEGIN
    SET @RemainingCount = 0;

    IF NOT EXISTS (SELECT 1 FROM DEPENDENT WHERE ESSN = @ESSN AND 	DEPENDENT_NAME = @DepName)
    BEGIN
        PRINT 'Dependent Record Not Found';
        RETURN;
    END;

    DELETE FROM DEPENDENT
    WHERE ESSN = @ESSN AND DEPENDENT_NAME = @DepName;

SELECT @RemainingCount = COUNT(*) FROM DEPENDENT WHERE ESSN = @ESSN;
END;
